name: Build and Release

on:
  workflow_dispatch:  # Ermöglicht das manuelle Auslösen
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release

      - name: Publish
        run: dotnet publish -c Release -r win-x64 --self-contained

      - name: Get current tag
        id: get_tag
        run: |
          if ("${{ github.ref }}" -like "refs/tags/*") {
          echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
          } else {
          echo "::set-output name=tag::v1.0.0"
          }

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          release_name: Release ${{ steps.get_tag.outputs.tag }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .exe to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Nt.Utility/bin/Release/net6.0-windows/win-x64/publish/Nt.Utility.exe
          asset_name: Nt.Utility.exe
          asset_content_type: application/octet-stream
